spring.application.name=GymCRM

# Banco H2 em memória (os dados somem ao reiniciar a aplicação)
spring.datasource.url=jdbc:h2:mem:financas
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Console do H2: http://localhost:8080/h2-console
spring.h2.console.enabled=true
